### ISSUE TITLE
Help needed : pandas.errors.InvalidIndexError

### ISSUE THREAD

**Issue by RJDan** [laneatmore/BAMscorer#1]
Hello 
I need some help troubleshooting an error I get when running the final step of bamscorer.
I don't code in python so it is a bit tricky for me to figure out what the error message means or where it likely comes from.

```
[.....]
Number of loci scored: 
1394
Finished reading bam for: 1701-445.sort
Number of loci scored: 
1411
Finished reading bam for: 1701-561.sort
Number of loci scored: 
875
pandas.errors.InvalidIndexError: [  0   2   3   4   7   8  11  12  13  14  16  18  19  20  21  22  23  24
  25  26  28  31  32  37  39  40  41  42  43  44  45  46  48  49  50  55
  58  60  61  62  63  64  65  67  68  69  76  78  80  86  87  88  89  90
  91  92  93  94  95  98  99 103 104 105 106 107 108 109 111 112 113 114
 117 121 122 124 127 128 129]

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/rdaniels/.local/bin/BAMscorer", line 1486, in <module>
    main()
  File "/home/rdaniels/.local/bin/BAMscorer", line 989, in main
    bam_scoring(PWD, OUT)
  File "/home/rdaniels/.local/bin/BAMscorer", line 751, in bam_scoring
    matching.at[np.array(matched_idx_DA_AA),'NEW_AF_AA'] = matching['AF_AA']
  File "/home/rdaniels/Projects/23_herringlowpass/HPC/Analyses/python39-env/lib/python3.9/site-packages/pandas/core/indexing.py", line 2579, in __setitem__
    return super().__setitem__(key, value)
  File "/home/rdaniels/Projects/23_herringlowpass/HPC/Analyses/python39-env/lib/python3.9/site-packages/pandas/core/indexing.py", line 2535, in __setitem__
    self.obj._set_value(*key, value=value, takeable=self._takeable)
  File "/home/rdaniels/Projects/23_herringlowpass/HPC/Analyses/python39-env/lib/python3.9/site-packages/pandas/core/frame.py", line 4569, in _set_value
    raise InvalidIndexError(
pandas.errors.InvalidIndexError: You can only assign a scalar value not a <class 'pandas.core.series.Series'>
(END)
```

**Comment by RJDan** [comment]
I get the same error with the test data provided in the git repo.

```
[...]
Number of loci scored: 
8
Finished reading bam for: COD053.sample
Number of loci scored: 
1
BAM calling finished
Traceback (most recent call last):
  File "/home/rdaniels/Projects/23_herringlowpass/HPC/Analyses/python39-env/lib/python3.9/site-packages/pandas/core/frame.py", line 4550, in _set_value
    iindex = self.index.get_loc(index)
  File "/home/rdaniels/Projects/23_herringlowpass/HPC/Analyses/python39-env/lib/python3.9/site-packages/pandas/core/indexes/range.py", line 418, in get_loc
    self._check_indexing_error(key)
  File "/home/rdaniels/Projects/23_herringlowpass/HPC/Analyses/python39-env/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 6058, in _check_indexing_error
    raise InvalidIndexError(key)
pandas.errors.InvalidIndexError: [0 1 2 3 4 5 6 7]

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/rdaniels/.local/bin/BAMscorer", line 1486, in <module>
    main()
  File "/home/rdaniels/.local/bin/BAMscorer", line 989, in main
    bam_scoring(PWD, OUT)
  File "/home/rdaniels/.local/bin/BAMscorer", line 753, in bam_scoring
    matching.at[np.array(matched_idx_DA_BB),'NEW_AF_BB'] = matching['AF_BB']
  File "/home/rdaniels/Projects/23_herringlowpass/HPC/Analyses/python39-env/lib/python3.9/site-packages/pandas/core/indexing.py", line 2579, in __setitem__
    return super().__setitem__(key, value)
  File "/home/rdaniels/Projects/23_herringlowpass/HPC/Analyses/python39-env/lib/python3.9/site-packages/pandas/core/indexing.py", line 2535, in __setitem__
    self.obj._set_value(*key, value=value, takeable=self._takeable)
  File "/home/rdaniels/Projects/23_herringlowpass/HPC/Analyses/python39-env/lib/python3.9/site-packages/pandas/core/frame.py", line 4569, in _set_value
    raise InvalidIndexError(
pandas.errors.InvalidIndexError: You can only assign a scalar value not a <class 'pandas.core.series.Series'>
```

**Comment by laneatmore** [comment]
Hi Ryan, can you please provide your environment details (python version, package versions, etc) and the commands you're using to run BAMscorer?

**Comment by RJDan** [comment]
Hello 
Here are the environment details. I will post the commands shortly.

```
conda info --env

# conda environments:
#
python311-env            /home/rdaniels/.conda/envs/python311-env
python39-env          *  /home/rdaniels/Projects/23_herringlowpass/HPC/Analyses/python39-env
                         /home/rdaniels/Projects/23_herringsnp/HPC/Analyses/python39-env
base                     /sw/apps/conda/latest/rackham_stage
```


```
# packages in environment at /home/rdaniels/Projects/23_herringlowpass/HPC/Analyses/python39-env:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    file:///sw/apps/conda/latest/rackham/local_repo/conda-forge
_openmp_mutex             4.5                       2_gnu    file:///sw/apps/conda/latest/rackham/local_repo/conda-forge
bzip2                     1.0.8                hd590300_5    file:///sw/apps/conda/latest/rackham/local_repo/conda-forge
c-ares                    1.26.0               hd590300_0    conda-forge
ca-certificates           2023.11.17           hbcca054_0    file:///sw/apps/conda/latest/rackham/local_repo/conda-forge
keyutils                  1.6.1                h166bdaf_0    conda-forge
krb5                      1.21.2               h659d440_0    conda-forge
ld_impl_linux-64          2.40                 h41732ed_0    file:///sw/apps/conda/latest/rackham/local_repo/conda-forge
libblas                   3.9.0           21_linux64_openblas    conda-forge
libcblas                  3.9.0           21_linux64_openblas    conda-forge
libcurl                   8.5.0                hca28451_0    conda-forge
libdeflate                1.18                 h0b41bf4_0    conda-forge
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libev                     4.33                 hd590300_2    conda-forge
libffi                    3.4.2                h7f98852_5    file:///sw/apps/conda/latest/rackham/local_repo/conda-forge
libgcc-ng                 13.2.0               h807b86a_4    file:///sw/apps/conda/latest/rackham/local_repo/conda-forge
libgfortran-ng            13.2.0               h69a702a_4    conda-forge
libgfortran5              13.2.0               ha4646dd_4    conda-forge
libgomp                   13.2.0               h807b86a_4    file:///sw/apps/conda/latest/rackham/local_repo/conda-forge
liblapack                 3.9.0           21_linux64_openblas    conda-forge
libnghttp2                1.58.0               h47da74e_1    conda-forge
libnsl                    2.0.1                hd590300_0    file:///sw/apps/conda/latest/rackham/local_repo/conda-forge
libopenblas               0.3.26          pthreads_h413a1c8_0    conda-forge
libsqlite                 3.44.2               h2797004_0    file:///sw/apps/conda/latest/rackham/local_repo/conda-forge
libssh2                   1.11.0               h0841786_0    conda-forge
libstdcxx-ng              13.2.0               h7e041cc_4    conda-forge
libuuid                   2.38.1               h0b41bf4_0    file:///sw/apps/conda/latest/rackham/local_repo/conda-forge
libxcrypt                 4.4.36               hd590300_1    file:///sw/apps/conda/latest/rackham/local_repo/conda-forge
libzlib                   1.2.13               hd590300_5    file:///sw/apps/conda/latest/rackham/local_repo/conda-forge
ncurses                   6.4                  h59595ed_2    file:///sw/apps/conda/latest/rackham/local_repo/conda-forge
numpy                     1.26.3           py39h474f0d3_0    conda-forge
openssl                   3.2.0                hd590300_1    file:///sw/apps/conda/latest/rackham/local_repo/conda-forge
pandas                    2.2.0            py39hddac248_0    conda-forge
pip                       23.3.2             pyhd8ed1ab_0    file:///sw/apps/conda/latest/rackham/local_repo/conda-forge
pysam                     0.22.0           py39hcada746_0    bioconda
python                    3.9.18          h0755675_1_cpython    file:///sw/apps/conda/latest/rackham/local_repo/conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python-tzdata             2023.4             pyhd8ed1ab_0    conda-forge
python_abi                3.9                      4_cp39    conda-forge
pytz                      2023.4             pyhd8ed1ab_0    conda-forge
readline                  8.2                  h8228510_1    file:///sw/apps/conda/latest/rackham/local_repo/conda-forge
setuptools                69.0.3             pyhd8ed1ab_0    file:///sw/apps/conda/latest/rackham/local_repo/conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
tk                        8.6.13          noxft_h4845f30_101    file:///sw/apps/conda/latest/rackham/local_repo/conda-forge
tzdata                    2023d                h0c530f3_0    file:///sw/apps/conda/latest/rackham/local_repo/conda-forge
wheel                     0.42.0             pyhd8ed1ab_0    file:///sw/apps/conda/latest/rackham/local_repo/conda-forge
xz                        5.2.6                h166bdaf_0    file:///sw/apps/conda/latest/rackham/local_repo/conda-forge
zlib                      1.2.13               hd590300_5    conda-forge
zstd                      1.5.5                hfc55251_0    conda-forge
```


 ```
uname -a
Linux 3.10.0-1160.108.1.el7.x86_64 #1 SMP Thu Jan 25 16:17:31 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux```

**Comment by RJDan** [comment]
Step 1: Ref prep
```
vcftools --gzvcf ${REFVCF}.vcf.gz \
--max-missing 1 \
--min-alleles 2 \
--max-alleles 2 \
--maf 0.01\
--recode \
--stdout |\
bgzip > ${REFVCF}_biallelic_nomissing.vcf.gz

```

Step 2 : Get subset of ref file
SUBSET is a list of individuals to retain.
```
  vcftools --gzvcf  ${REFVCF}_biallelic_nomissing.vcf.gz \
--keep ${SUBSET} \
--recode \
--stdout |\
bgzip > ${OUTNAME}.vcf.gz

```
Step 3 : SNPselect
BAMSCORER=path/to/binary

```
python3.9 $BAMSCORER select_snps \
${OUTNAME}.vcf.gz \
${OUTPUTPRFX} \
--include ${BEDFILE} \
--numchrom 26 \
--map  ${MAPFILE}
```
Contents of MAPFILE
```
LG01 1
```
Contents of BEDFILE
```
CHR	START	END
LG01	9600097	26199636
```

Step4 : run BAMscore
```
python3.9 $BAMSCORER score_bams \
${OUTNAME}.vcf.gz \
${OUTPUTPRFX} \
${BAMDIR}

```
content of ${OUTPUTPRFX}_AA_individuals.txt
```
LOF1103011
LOF1403011
LOF1403014
LOF1403004
LOF1403008
LOF1403018
```

content of ${OUTPUTPRFX}_BB_individuals.txt
```
ORE1203016
KIE1103003
TVE120511
TVE130510
AVE1409016
LOW1503001
```
content of ${OUTPUTPRFX}_db_individuals.txt
```
LOF1103011
LOF1403011
LOF1403014
LOF1403004
LOF1403008
LOF1403018
ORE1203016
KIE1103003
TVE120511
TVE130510
AVE1409016
LOW1503001
```
Content of ${OUTPUTPRFX}.divergent.SNPs.txt

```LG01	9604539
LG01	9604540
LG01	9608422
LG01	9611379
LG01	9862991
LG01	10010226
LG01	10010227
LG01	10010247
LG01	10031706
LG01	10103871
LG01	10294310
LG01	10370333
LG01	10495852
LG01	10721164
LG01	10726730
LG01	10871612
LG01	10893995
LG01	10906522
LG01	10934512
LG01	10934584
LG01	10935317
LG01	10945796
LG01	10964603
LG01	10964653
LG01	10964674
LG01	10964684
LG01	10964695
LG01	10964801
LG01	10970349
LG01	11218199
LG01	11300218
LG01	11355465
LG01	11374679
LG01	11386343
LG01	11400300
LG01	11496666
LG01	11496680
LG01	11496743
LG01	11558713
LG01	11558732
LG01	11654627
LG01	11834920
LG01	12178105
LG01	12223814
LG01	12337010
LG01	12339432
LG01	12339476
LG01	12474204
LG01	12574079
LG01	12603041
LG01	12610756
LG01	12612152
LG01	12612154
LG01	12730967
LG01	12730968
LG01	12919901
LG01	12981995
LG01	13146730
LG01	13228279
LG01	13228287
LG01	13323097
LG01	13323917
LG01	13338363
LG01	13342151
LG01	13386491
LG01	13413264
LG01	13503277
LG01	13503619
LG01	13533391
LG01	13533406
LG01	13602017
LG01	13695516
LG01	13713163
LG01	13721226
LG01	13813191
LG01	13813209
LG01	14108087
LG01	14113896
LG01	14183821
LG01	14593206
LG01	14822400
LG01	14920410
LG01	14985783
LG01	14986391
LG01	14989753
LG01	15005864
LG01	15006030
LG01	15006035
LG01	15329479
LG01	15363673
LG01	15485732
LG01	15537884
LG01	15545593
LG01	15596611
LG01	15615697
LG01	15618828
LG01	15709974
LG01	15738382
LG01	15904127
LG01	15940343
LG01	15961146
LG01	16005806
LG01	16058017
LG01	16058770
LG01	16060916
LG01	16063345
LG01	16065885
LG01	16065967
LG01	16065971
LG01	16073934
LG01	16073976
LG01	16074285
LG01	16074429
LG01	16074432
LG01	16075325
LG01	16075671
LG01	16075812
LG01	16076069
LG01	16079831
LG01	16080232
LG01	16199969
LG01	16200301
LG01	16240602
LG01	16240698
LG01	16361074
LG01	16431953
LG01	16468039
LG01	16506258
LG01	16550805
LG01	16567910
LG01	16583203
LG01	16653263
LG01	16710595
LG01	16767171
LG01	17087711
LG01	17248110
LG01	17318931
LG01	17318969
LG01	17320979
LG01	17322274
LG01	17378390
LG01	17380899
LG01	17407032
LG01	17490441
LG01	17596995
LG01	17619959
LG01	17683720
LG01	17696965
LG01	17851239
LG01	17859873
LG01	17904343
LG01	18179419
LG01	18179420
LG01	18189948
LG01	18286234
LG01	18306849
LG01	18366239
LG01	18445957
LG01	18458822
LG01	18556742
LG01	18580925
LG01	18668541
LG01	18669726
LG01	18674458
LG01	18692622
LG01	18704694
LG01	18714994
LG01	18715132
LG01	18718744
LG01	18740868
LG01	18846124
LG01	19061647
LG01	19061651
LG01	19077126
LG01	19123732
LG01	19126133
LG01	19148648
LG01	19174679
LG01	19198742
LG01	19211755
LG01	19240873
LG01	19278898
LG01	19390358
LG01	19463153
LG01	19482685
LG01	19489760
LG01	19710097
LG01	19722743
LG01	19857355
LG01	19872637
LG01	19884618
LG01	19909410
LG01	19966945
LG01	19967636
LG01	20002303
LG01	20002334
LG01	20004429
LG01	20092117
LG01	20125809
LG01	20152862
LG01	20152884
LG01	20243508
LG01	20272697
LG01	20466799
LG01	20473222
LG01	20514201
LG01	20588902
LG01	20621191
LG01	20712649
LG01	20715226
LG01	20788095
LG01	20848222
LG01	20912846
LG01	20925672
LG01	21039242
LG01	21060219
LG01	21127407
LG01	21183548
LG01	21270136
LG01	21275752
LG01	21452435
LG01	21452476
LG01	21561483
LG01	21668011
LG01	21918473
LG01	22149024
LG01	22149078
LG01	22149079
LG01	22149088
LG01	22149956
LG01	22151844
LG01	22153765
LG01	22154498
LG01	22154732
LG01	22158782
LG01	22158783
LG01	22158897
LG01	22165175
LG01	22165964
LG01	22166782
LG01	22166793
LG01	22166860
LG01	22166864
LG01	22167155
LG01	22167204
LG01	22168155
LG01	22168264
LG01	22168270
LG01	22224885
LG01	22231734
LG01	22254115
LG01	22478248
LG01	22857614
LG01	22984106
LG01	23158345
LG01	23343480
LG01	23611434
LG01	23631240
LG01	23707566
LG01	24597697
LG01	24646022
LG01	24703473
LG01	25210799
LG01	25242133
LG01	25351556
LG01	25351558
LG01	25351584
LG01	25351591
LG01	25351596
LG01	25455536
LG01	25474901
LG01	25614514
LG01	25635295
LG01	25944362
```

**Comment by RJDan** [comment]
To clarify, these are the commands used for the test data that comes in the git repo.

**Comment by laneatmore** [comment]
Thanks, I'll see if I can replicate your problem. You are using BAMscorer v1.5 for Linux, right?

**Comment by RJDan** [comment]
Yes, thats correct!
Thanks for the help!

**Comment by laneatmore** [comment]
Try downgrading pandas to 1.3.5 instead of 2.2.2. Pandas 2 has a different indexing method and BAMscorer was built with pandas 1. After upgrading my environment to pandas 2 I was able to replicate your error. 

I'll put a note on the readme and provide a patch for pandas 2 compatibility at a later date

**Comment by laneatmore** [comment]
BAMscorer v1.6 for linux is now online and compatible with pandas 2 :)

**Comment by RJDan** [comment]
I will test it shortly!

**Comment by RJDan** [comment]
Hello 
I could not confirm that the change has worked. I have a new problem. I will create a new issue for it.

**Comment by RJDan** [comment]
I have successfully run the example dataset with v1.6.
Thanks again for the help!
