### ISSUE TITLE
*.het file not written in v1.6

### ISSUE THREAD

**Issue by RJDan** [laneatmore/BAMscorer#2]
Hello 
I have a new problem since moving to v1.6. 
The select_snps function does not print out the *.divergent_SNPs.txt file.  
The *.het file is empty.
I guess this has to do with vcftools but there is no indication of what went wrong with vcftools (see the log file below). 
I am running things on our hpc so I don't see what else is printed to screen.

The code is the same as I ran in issue: https://github.com/laneatmore/BAMscorer/issues/1#issue-2122952018

```
[...]
        --positions LG01_LG01_9600098_26199637_TestRegion_TestData_testdata.divergent_SNPs.txt

Using zlib version: 1.2.11
Warning: Expected at least 2 parts in FORMAT entry: ID=PGT,Number=1,Type=String,Description="Physical phasing haplotype information, describing how the alternate alleles are phased in relation to one another">
Warning: Expected at least 2 parts in FORMAT entry: ID=PID,Number=1,Type=String,Description="Physical phasing ID information, where each unique ID within a given sample (but not across samples) connects records within a phasing group">
Warning: Expected at least 2 parts in FORMAT entry: ID=PL,Number=G,Type=Integer,Description="Normalized, Phred-scaled likelihoods for genotypes as defined in the VCF specification">
Warning: Expected at least 2 parts in FORMAT entry: ID=RGQ,Number=1,Type=Integer,Description="Unconditional reference genotype confidence, encoded as a phred quality -10*log10 p(genotype call is wrong)">
Warning: Expected at least 2 parts in INFO entry: ID=AC,Number=A,Type=Integer,Description="Allele count in genotypes, for each ALT allele, in the same order as listed">
Warning: Expected at least 2 parts in INFO entry: ID=AC,Number=A,Type=Integer,Description="Allele count in genotypes, for each ALT allele, in the same order as listed">
Warning: Expected at least 2 parts in INFO entry: ID=AF,Number=A,Type=Float,Description="Allele Frequency, for each ALT allele, in the same order as listed">
Warning: Expected at least 2 parts in INFO entry: ID=AF,Number=A,Type=Float,Description="Allele Frequency, for each ALT allele, in the same order as listed">
Warning: Expected at least 2 parts in INFO entry: ID=MLEAC,Number=A,Type=Integer,Description="Maximum likelihood expectation (MLE) for the allele counts (not necessarily the same as the AC), for each ALT allele, in the same order as listed">
Warning: Expected at least 2 parts in INFO entry: ID=MLEAC,Number=A,Type=Integer,Description="Maximum likelihood expectation (MLE) for the allele counts (not necessarily the same as the AC), for each ALT allele, in the same order as listed">
Warning: Expected at least 2 parts in INFO entry: ID=MLEAF,Number=A,Type=Float,Description="Maximum likelihood expectation (MLE) for the allele frequency (not necessarily the same as the AF), for each ALT allele, in the same order as listed">
Warning: Expected at least 2 parts in INFO entry: ID=MLEAF,Number=A,Type=Float,Description="Maximum likelihood expectation (MLE) for the allele frequency (not necessarily the same as the AF), for each ALT allele, in the same order as listed">
After filtering, kept 12 out of 12 Individuals
Outputting Individual Heterozygosity
Error: Could not open Positions file: LG01_LG01_9600098_26199637_TestRegion_TestData_testdata.divergent_SNPs.txt
Traceback (most recent call last):
  File "/home/rdaniels/.local/bin/BAMscorer", line 1483, in <module>
    main()
  File "/home/rdaniels/.local/bin/BAMscorer", line 418, in main
    pca_het(OUT)
  File "/home/rdaniels/.local/bin/BAMscorer", line 374, in pca_het
    pc1_txt['het'] = het['F'].values
  File "/home/rdaniels/Projects/23_herringlowpass/HPC/Analyses/python39-env/lib/python3.9/site-packages/pandas/core/frame.py", line 4299, in __setitem__
    self._set_item(key, value)
  File "/home/rdaniels/Projects/23_herringlowpass/HPC/Analyses/python39-env/lib/python3.9/site-packages/pandas/core/frame.py", line 4512, in _set_item
    value, refs = self._sanitize_column(value)
  File "/home/rdaniels/Projects/23_herringlowpass/HPC/Analyses/python39-env/lib/python3.9/site-packages/pandas/core/frame.py", line 5253, in _sanitize_column
    com.require_length_match(value, self.index)
  File "/home/rdaniels/Projects/23_herringlowpass/HPC/Analyses/python39-env/lib/python3.9/site-packages/pandas/core/common.py", line 571, in require_length_match
    raise ValueError(
ValueError: Length of values (0) does not match length of index (12)
```

**Comment by RJDan** [comment]
Sorry, I made a mistake. It has nothing to do with the output name. I restarted with a clean folder and I get the same error message when using the LG01 as output name.

 ============================================

#### Previous post below

After trying different subsets etc. it seems that if I use a file name other than 'LG01' for the output, I will get an error.
For example 


```
[...]
After filtering, kept 12 out of 12 Individuals
Outputting Individual Heterozygosity
Error: Could not open Positions file: LG01_testdata.divergent_SNPs.txt
Traceback (most recent call last):
  File "/home/rdaniels/.local/bin/BAMscorer", line 1483, in <module>
    main()
  File "/home/rdaniels/.local/bin/BAMscorer", line 418, in main
    pca_het(OUT)
  File "/home/rdaniels/.local/bin/BAMscorer", line 374, in pca_het
    pc1_txt['het'] = het['F'].values
  File "/home/rdaniels/Projects/23_herringlowpass/HPC/Analyses/python39-env/lib/python3.9/site-packages/pandas/core/frame.py", line 4299, in __setitem__
    self._set_item(key, value)
  File "/home/rdaniels/Projects/23_herringlowpass/HPC/Analyses/python39-env/lib/python3.9/site-packages/pandas/core/frame.py", line 4512, in _set_item
    value, refs = self._sanitize_column(value)
  File "/home/rdaniels/Projects/23_herringlowpass/HPC/Analyses/python39-env/lib/python3.9/site-packages/pandas/core/frame.py", line 5253, in _sanitize_column
    com.require_length_match(value, self.index)
  File "/home/rdaniels/Projects/23_herringlowpass/HPC/Analyses/python39-env/lib/python3.9/site-packages/pandas/core/common.py", line 571, in require_length_match
    raise ValueError(
ValueError: Length of values (0) does not match length of index (12)

```
It seems like LG01 has been hard coded somewhere in the binary.

**Comment by laneatmore** [comment]
Hi Ryan, I've tested different arguments and prefixes and am unable to replicate this error with BAMscorer v1.6. I don't think there's anything going wrong with VCFtools. There is likely an error earlier in the output that should tell you what the issue is (e.g., dependencies not installed, mismatched filenames). The most likely reason the *.divergent_snps.txt file is not found is because it was never created, which only happens if smartPCA or PLINK is not found for some reason. You can run the test dataset on the command line without submitting a job, so you should be able to see all the output.

**Comment by RJDan** [comment]
Hello
Thank you for having a look. I think I will try downgrading to use 1.5 but I wanted to update here incase it helps.

I reran the commands directly in an interactive slurm session (so no variables or scripts) and I got the same issue as before. 
I don't think it is an issue with plink or smartpca not being available as the output (below) includes output from both.

Here is the command:
```
(/home/rdaniels/Projects/23_herringlowpass/HPC/Analyses/python39-env) [rdaniels@r483 BAMscore_Test]$ python3.9 ~/.local/bin/BAMscorer select_snps LG01_testdata.vcf.gz LG01_out --map chrom_map 

```
Here are the files in the dir before running the command (all files from the git repo):

```
BAMs  chrom_map  LG01_testdata.vcf.gz  LG01_testdata.vcf.gz.tbi
```

Here are the loaded modules:
```
 1) uppmax   2) bioinfo-tools   3) ANGSD/0.921   4) bcftools/1.19   5) vcftools/0.1.16   6) conda/latest   7) plink/1.90b4.9   8) eigensoft/7.2.1   9) samtools/1.19
```

Here is the output:
```
/home/rdaniels/.local/bin/BAMscorer:9: DeprecationWarning: 
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466
        
  import pandas as pd
running BAMscorer with: LG01_testdata.vcf.gz LG01_out --map chrom_map
Prepping VCF

VCFtools - 0.1.16
(C) Adam Auton and Anthony Marcketta 2009

Parameters as interpreted:
	--gzvcf LG01_testdata.vcf.gz
	--chrom-map chrom_map
	--out LG01_out
	--plink

Using zlib version: 1.2.11
Warning: Expected at least 2 parts in FORMAT entry: ID=PGT,Number=1,Type=String,Description="Physical phasing haplotype information, describing how the alternate alleles are phased in relation to one another">
Warning: Expected at least 2 parts in FORMAT entry: ID=PID,Number=1,Type=String,Description="Physical phasing ID information, where each unique ID within a given sample (but not across samples) connects records within a phasing group">
Warning: Expected at least 2 parts in FORMAT entry: ID=PL,Number=G,Type=Integer,Description="Normalized, Phred-scaled likelihoods for genotypes as defined in the VCF specification">
Warning: Expected at least 2 parts in FORMAT entry: ID=RGQ,Number=1,Type=Integer,Description="Unconditional reference genotype confidence, encoded as a phred quality -10*log10 p(genotype call is wrong)">
Warning: Expected at least 2 parts in INFO entry: ID=AC,Number=A,Type=Integer,Description="Allele count in genotypes, for each ALT allele, in the same order as listed">
Warning: Expected at least 2 parts in INFO entry: ID=AC,Number=A,Type=Integer,Description="Allele count in genotypes, for each ALT allele, in the same order as listed">
Warning: Expected at least 2 parts in INFO entry: ID=AF,Number=A,Type=Float,Description="Allele Frequency, for each ALT allele, in the same order as listed">
Warning: Expected at least 2 parts in INFO entry: ID=AF,Number=A,Type=Float,Description="Allele Frequency, for each ALT allele, in the same order as listed">
Warning: Expected at least 2 parts in INFO entry: ID=MLEAC,Number=A,Type=Integer,Description="Maximum likelihood expectation (MLE) for the allele counts (not necessarily the same as the AC), for each ALT allele, in the same order as listed">
Warning: Expected at least 2 parts in INFO entry: ID=MLEAC,Number=A,Type=Integer,Description="Maximum likelihood expectation (MLE) for the allele counts (not necessarily the same as the AC), for each ALT allele, in the same order as listed">
Warning: Expected at least 2 parts in INFO entry: ID=MLEAF,Number=A,Type=Float,Description="Maximum likelihood expectation (MLE) for the allele frequency (not necessarily the same as the AF), for each ALT allele, in the same order as listed">
Warning: Expected at least 2 parts in INFO entry: ID=MLEAF,Number=A,Type=Float,Description="Maximum likelihood expectation (MLE) for the allele frequency (not necessarily the same as the AF), for each ALT allele, in the same order as listed">
After filtering, kept 12 out of 12 Individuals
Writing PLINK PED and MAP files ... 
	Read 1 chromosome mapping file entries.
Done.
After filtering, kept 384531 out of a possible 384531 Sites
Run Time = 4.00 seconds
PLINK v1.90b4.9 64-bit (13 Oct 2017)           www.cog-genomics.org/plink/1.9/
(C) 2005-2017 Shaun Purcell, Christopher Chang   GNU General Public License v3
Logging to LG01_out.log.
Options in effect:
  --allow-extra-chr
  --double-id
  --file LG01_out
  --keep-allele-order
  --make-bed
  --out LG01_out
  --set-missing-var-ids @:#

128373 MB RAM detected; reserving 64186 MB for main workspace.
.ped scan complete (for binary autoconversion).
Performing single-pass .bed write (384531 variants, 12 people).
--file: LG01_out-temporary.bed + LG01_out-temporary.bim +
LG01_out-temporary.fam written.
384531 variants loaded from .bim file.
12 people (0 males, 0 females, 12 ambiguous) loaded from .fam.
Ambiguous sex IDs written to LG01_out.nosex .
Using 1 thread (no multithreaded calculations invoked).
Before main variant filters, 12 founders and 0 nonfounders present.
Calculating allele frequencies... done.
Total genotyping rate is 0.768959.
384531 variants and 12 people pass filters and QC.
Note: No phenotypes present.
--make-bed to LG01_out.bed + LG01_out.bim + LG01_out.fam ... done.
VCF converted to PLINK with chrom_map
parameter file: LG01_out.params.txt
genotypename: LG01_out.bed
snpname: LG01_out.bim
indivname: LG01_out.fam
outputformat: PACKEDANCESTRYMAP
genooutfilename: LG01_out.geno
snpoutfilename: LG01_out.snp
indoutfilename: LG01_out.ind
numchrom: 22
genetic distance set from physical distance
genotype file processed
numvalidind:     12  maxmiss: 12001
packedancestrymap output
##end of convertf run

VCFtools - 0.1.16
(C) Adam Auton and Anthony Marcketta 2009

Parameters as interpreted:
	--gzvcf LG01_testdata.vcf.gz
	--het
	--out LG01_out
	--positions LG01_out.divergent_SNPs.txt

Using zlib version: 1.2.11
Warning: Expected at least 2 parts in FORMAT entry: ID=PGT,Number=1,Type=String,Description="Physical phasing haplotype information, describing how the alternate alleles are phased in relation to one another">
Warning: Expected at least 2 parts in FORMAT entry: ID=PID,Number=1,Type=String,Description="Physical phasing ID information, where each unique ID within a given sample (but not across samples) connects records within a phasing group">
Warning: Expected at least 2 parts in FORMAT entry: ID=PL,Number=G,Type=Integer,Description="Normalized, Phred-scaled likelihoods for genotypes as defined in the VCF specification">
Warning: Expected at least 2 parts in FORMAT entry: ID=RGQ,Number=1,Type=Integer,Description="Unconditional reference genotype confidence, encoded as a phred quality -10*log10 p(genotype call is wrong)">
Warning: Expected at least 2 parts in INFO entry: ID=AC,Number=A,Type=Integer,Description="Allele count in genotypes, for each ALT allele, in the same order as listed">
Warning: Expected at least 2 parts in INFO entry: ID=AC,Number=A,Type=Integer,Description="Allele count in genotypes, for each ALT allele, in the same order as listed">
Warning: Expected at least 2 parts in INFO entry: ID=AF,Number=A,Type=Float,Description="Allele Frequency, for each ALT allele, in the same order as listed">
Warning: Expected at least 2 parts in INFO entry: ID=AF,Number=A,Type=Float,Description="Allele Frequency, for each ALT allele, in the same order as listed">
Warning: Expected at least 2 parts in INFO entry: ID=MLEAC,Number=A,Type=Integer,Description="Maximum likelihood expectation (MLE) for the allele counts (not necessarily the same as the AC), for each ALT allele, in the same order as listed">
Warning: Expected at least 2 parts in INFO entry: ID=MLEAC,Number=A,Type=Integer,Description="Maximum likelihood expectation (MLE) for the allele counts (not necessarily the same as the AC), for each ALT allele, in the same order as listed">
Warning: Expected at least 2 parts in INFO entry: ID=MLEAF,Number=A,Type=Float,Description="Maximum likelihood expectation (MLE) for the allele frequency (not necessarily the same as the AF), for each ALT allele, in the same order as listed">
Warning: Expected at least 2 parts in INFO entry: ID=MLEAF,Number=A,Type=Float,Description="Maximum likelihood expectation (MLE) for the allele frequency (not necessarily the same as the AF), for each ALT allele, in the same order as listed">
After filtering, kept 12 out of 12 Individuals
Outputting Individual Heterozygosity
Error: Could not open Positions file: LG01_out.divergent_SNPs.txt
Traceback (most recent call last):
  File "/home/rdaniels/.local/bin/BAMscorer", line 1483, in <module>
    main()
  File "/home/rdaniels/.local/bin/BAMscorer", line 418, in main
    pca_het(OUT)
  File "/home/rdaniels/.local/bin/BAMscorer", line 374, in pca_het
    pc1_txt['het'] = het['F'].values
  File "/home/rdaniels/Projects/23_herringlowpass/HPC/Analyses/python39-env/lib/python3.9/site-packages/pandas/core/frame.py", line 4299, in __setitem__
    self._set_item(key, value)
  File "/home/rdaniels/Projects/23_herringlowpass/HPC/Analyses/python39-env/lib/python3.9/site-packages/pandas/core/frame.py", line 4512, in _set_item
    value, refs = self._sanitize_column(value)
  File "/home/rdaniels/Projects/23_herringlowpass/HPC/Analyses/python39-env/lib/python3.9/site-packages/pandas/core/frame.py", line 5253, in _sanitize_column
    com.require_length_match(value, self.index)
  File "/home/rdaniels/Projects/23_herringlowpass/HPC/Analyses/python39-env/lib/python3.9/site-packages/pandas/core/common.py", line 571, in require_length_match
    raise ValueError(
ValueError: Length of values (0) does not match length of index (12)
```

**Comment by RJDan** [comment]
What command writes the LG01_out.divergent_SNPs.txt file?

**Comment by laneatmore** [comment]
Hi Ryan, thanks for the update. The divergent SNPs output is created with the output from smartPCA. I re-downloaded BAMscorer 1.6 and was able to reproduce this error, there was a small typo in the most recent argparsing. I've now updated this. You should see "Divergent SNPs database created" as a message after smartPCA runs if you retry with the most recent 1.6 

Otherwise 1.5 works just fine :)

**Comment by RJDan** [comment]
The pca_het.txt file is now printed in v1.6. Thank you!
